"""One-command entry point for the seminar project.

Examples
--------
Fast, fully self-contained demonstration:
    python scripts/run_replication.py --data synthetic --quick --regenerate

Full model list on synthetic data (slow):
    python scripts/run_replication.py --data synthetic --models all

Real data already placed in data/raw/:
    python scripts/run_replication.py --data real --models all

Synthetic outputs are never described as empirical replication results.
"""
from __future__ import annotations

from copy import deepcopy
from pathlib import Path
import argparse
import json
import sys

import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from factor_zoo.data.loaders import normalize_month_end, read_table
from factor_zoo.data.panel import build_model_panel
from factor_zoo.data.synthetic import SyntheticSpec, generate_synthetic_raw
from factor_zoo.evaluation.compare import compare_monthly_r2
from factor_zoo.evaluation.subsamples import evaluate_subsamples
from factor_zoo.portfolio.costs import apply_turnover_costs
from factor_zoo.portfolio.performance import stats
from factor_zoo.portfolio.sorts import portfolio_holdings, portfolio_returns
from factor_zoo.training.runner import run_expanding_experiment
from factor_zoo.utils.io import load_yaml


def quicken_model_config(cfg: dict) -> dict:
    """Reduce compute only; the feature construction and time split remain unchanged."""
    cfg = deepcopy(cfg)
    for name in ("ols_h", "ols3_h", "lasso_h", "enet_h"):
        cfg["models"][name]["epochs"] = 12
        cfg["models"][name]["patience"] = 3
    cfg["models"]["pls"]["n_components_grid"] = [5]
    cfg["models"]["gbrt_h"]["max_depth_grid"] = [2]
    cfg["models"]["gbrt_h"]["max_iter_grid"] = [20]
    cfg["models"]["gbrt_h"]["learning_rate_grid"] = [0.05]
    cfg["models"]["rf"]["max_depth_grid"] = [3]
    cfg["models"]["rf"]["n_estimators_grid"] = [8]
    cfg["models"]["rf"]["max_features_grid"] = [20]
    cfg["models"]["vasa"]["n_submodels_grid"] = [15]
    cfg["models"]["vasa"]["n_components_grid"] = [20]
    d = cfg["neural_defaults"]
    d["l1_grid"] = [1e-4]
    d["lr_grid"] = [1e-3]
    d["batch_size_grid"] = [4096]
    d["dropout_grid"] = [0.1]
    d["epochs"] = 8
    d["patience"] = 2
    d["ensemble"] = 1
    return cfg


def paths_for_mode(mode: str):
    if mode == "synthetic":
        return ROOT / "data/synthetic/raw", ROOT / "data/synthetic/processed", ROOT / "outputs/synthetic"
    return ROOT / "data/raw", ROOT / "data/processed", ROOT / "outputs/real"


def find_table(raw_dir: Path, stem: str) -> Path:
    for suffix in (".parquet", ".csv"):
        p = raw_dir / f"{stem}{suffix}"
        if p.exists():
            return p
    raise FileNotFoundError(f"Missing {stem}.parquet/.csv in {raw_dir}")


def load_raw(raw_dir: Path):
    c = normalize_month_end(read_table(find_table(raw_dir, "stock_characteristics")))
    m = normalize_month_end(read_table(find_table(raw_dir, "macro")))
    r = normalize_month_end(read_table(find_table(raw_dir, "monthly_returns")))
    return c, m, r


def save_frame(frame: pd.DataFrame, base: Path) -> Path:
    """Prefer Parquet; CSV fallback keeps the demo runnable without pyarrow."""
    try:
        path = base.with_suffix(".parquet")
        frame.to_parquet(path, index=False)
    except (ImportError, ModuleNotFoundError):
        path = base.with_suffix(".csv")
        frame.to_csv(path, index=False)
    return path


def load_frame(base: Path) -> pd.DataFrame:
    for suffix in (".parquet", ".csv"):
        p = base.with_suffix(suffix)
        if p.exists():
            return pd.read_parquet(p) if suffix == ".parquet" else pd.read_csv(p, parse_dates=["date"])
    raise FileNotFoundError(base)


def write_results_markdown(out_dir: Path, mode: str, r2_table: pd.DataFrame, portfolio_summary: pd.DataFrame, comparison: pd.DataFrame):
    lines = [
        f"# {'Synthetic demonstration' if mode == 'synthetic' else 'Empirical replication'} results",
        "",
    ]
    if mode == "synthetic":
        lines += [
            "> **Important:** these values are generated by this repository on synthetic data. They are not claimed to reproduce the paper's WIND/CSMAR estimates.",
            "",
        ]
    r2_display = r2_table.copy()
    for col in r2_display.columns:
        if col != "model":
            r2_display[col] = 100.0 * r2_display[col]
    lines += ["## Out-of-sample R² (%)", "", r2_display.to_markdown(index=False, floatfmt=".3f"), ""]
    if not portfolio_summary.empty:
        p0 = portfolio_summary[portfolio_summary.cost_bps == 0].copy()
        keep = ["model", "strategy", "avg_monthly", "sharpe_ann"]
        lines += ["## Portfolios (0 bps)", "", p0[keep].to_markdown(index=False), ""]
    if not comparison.empty:
        c = comparison[comparison.group == "all"].copy()
        keep = ["model", "paper_pct", "synthetic_pct" if mode == "synthetic" else "replication_pct", "abs_diff_pp"]
        lines += [
            "## Paper reference vs this run",
            "",
            "This table is diagnostic only. A synthetic run is expected to differ because its data-generating process is not the paper's dataset.",
            "",
            c[keep].to_markdown(index=False),
            "",
        ]
    (out_dir / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", choices=["synthetic", "real"], default="synthetic")
    ap.add_argument("--quick", action="store_true", help="Use a small compute budget; methodology and 1,160-feature construction stay the same.")
    ap.add_argument("--regenerate", action="store_true", help="Regenerate synthetic raw data.")
    ap.add_argument("--n-stocks", type=int, default=None)
    ap.add_argument("--models", nargs="+", default=None, help="Model names or the single word 'all'.")
    ap.add_argument("--append", action="store_true", help="Keep existing prediction files and combine them with this run.")
    args = ap.parse_args()

    raw_dir, processed_dir, out_dir = paths_for_mode(args.data)
    processed_dir.mkdir(parents=True, exist_ok=True)
    for sub in ["predictions", "tables", "figures"]:
        (out_dir / sub).mkdir(parents=True, exist_ok=True)

    synth_cfg = load_yaml(ROOT / "configs/synthetic.yaml")
    has_synth = any((raw_dir / f"stock_characteristics{s}").exists() for s in (".parquet", ".csv"))
    if args.data == "synthetic" and (args.regenerate or not has_synth):
        spec = SyntheticSpec(
            n_stocks=args.n_stocks or int(synth_cfg["n_stocks"]),
            start=str(synth_cfg["start"]),
            end=str(synth_cfg["end"]),
            seed=int(synth_cfg["seed"]),
            signal_monthly_std=float(synth_cfg["signal_monthly_std"]),
            idiosyncratic_monthly_std=float(synth_cfg["idiosyncratic_monthly_std"]),
            market_monthly_std=float(synth_cfg["market_monthly_std"]),
        )
        meta = generate_synthetic_raw(raw_dir, spec)
        print(f"[1/5] generated synthetic raw data: {meta['n_rows']:,} stock-month rows")
    elif args.data == "synthetic":
        print("[1/5] using existing synthetic raw data")
    else:
        print("[1/5] using data/raw (WIND/CSMAR/NBS-compatible exports expected)")

    # 1) Build exactly the same model panel for either data source.
    c, m, r = load_raw(raw_dir)
    panel, features = build_model_panel(c, m, r, expected_industries=80)
    try:
        panel_path = processed_dir / "model_panel.parquet"
        panel.to_parquet(panel_path, index=False)
    except (ImportError, ModuleNotFoundError):
        panel_path = processed_dir / "model_panel.pkl"
        panel.to_pickle(panel_path)
    (processed_dir / "feature_columns.json").write_text(json.dumps(features, indent=2), encoding="utf-8")
    print(f"[2/5] panel: {len(panel):,} rows, {len(features)} predictors")

    model_cfg = load_yaml(ROOT / "configs/models.yaml")
    if args.quick:
        model_cfg = quicken_model_config(model_cfg)
    exp_cfg = load_yaml(ROOT / "configs/experiment.yaml")

    if args.models == ["all"]:
        models = list(synth_cfg["full_models"])
    elif args.models:
        models = args.models
    else:
        models = list(synth_cfg["quick_models"] if args.quick else synth_cfg["full_models"])

    # Avoid stale files by default. --append is useful when building a demo one
    # model at a time on a slower laptop.
    if not args.append:
        for p in (out_dir / "predictions").glob("*"):
            if p.is_file():
                p.unlink()

    # 2) Train/validate/test with the paper's expanding temporal scheme.
    for i, name in enumerate(models, 1):
        pred, chosen = run_expanding_experiment(
            panel, features, name, model_cfg, exp_cfg,
            max_candidates=1 if args.quick else None,
        )
        save_frame(pred, out_dir / "predictions" / name)
        (out_dir / "predictions" / f"{name}_params.json").write_text(json.dumps(chosen, indent=2), encoding="utf-8")
        print(f"[3/5] model {i}/{len(models)}: {name} -> {len(pred):,} test predictions")

    # 3) Statistical evaluation. When --append is used, include previously
    # completed models that are still present in the prediction directory.
    existing = []
    for p in (out_dir / "predictions").glob("*"):
        if p.suffix in {".csv", ".parquet"}:
            existing.append(p.stem)
    eval_models = sorted(set(models + existing))

    r2_rows = []
    for name in eval_models:
        pred = load_frame(out_dir / "predictions" / name)
        row = {"model": name}
        row.update(evaluate_subsamples(pred))
        r2_rows.append(row)
    r2_table = pd.DataFrame(r2_rows).sort_values("model")
    r2_table.to_csv(out_dir / "tables" / "r2_oos.csv", index=False)

    comparison = compare_monthly_r2(r2_table)
    if args.data == "synthetic" and not comparison.empty:
        comparison = comparison.rename(columns={"replication_pct": "synthetic_pct"})
    comparison.to_csv(out_dir / "tables" / "paper_vs_run.csv", index=False)

    # 4) Portfolio analysis with actual next-month total returns and turnover costs.
    portfolio_rows = []
    cumulative = {}
    for name in eval_models:
        pred = load_frame(out_dir / "predictions" / name)
        if "market_cap" not in pred or "future_return" not in pred:
            continue
        holdings = portfolio_holdings(pred, weight_col="market_cap")
        pr = portfolio_returns(pred, weight_col="market_cap", ret_col="future_return")
        pr.to_csv(out_dir / "tables" / f"portfolio_{name}.csv", index=False)
        cumulative[name] = pr.set_index("date")["long_only"]
        for bps in [0, 20, 40, 60, 80]:
            net = apply_turnover_costs(pr, holdings, bps)
            for strategy in ["long_only", "long_short"]:
                s = stats(net[f"{strategy}_net_{bps}bps"])
                portfolio_rows.append({"model": name, "strategy": strategy, "cost_bps": bps, **s})
    portfolio_summary = pd.DataFrame(portfolio_rows)
    portfolio_summary.to_csv(out_dir / "tables" / "portfolio_summary.csv", index=False)

    # One clean comparison figure instead of dozens of files.
    if cumulative:
        fig, ax = plt.subplots(figsize=(10, 5.5))
        for name, series in cumulative.items():
            ax.plot(pd.to_datetime(series.index), (1.0 + series).cumprod(), label=name)
        ax.set(title="Long-only D10 portfolios", xlabel="Date", ylabel="Growth of 1")
        ax.legend(ncol=2, fontsize=8)
        fig.tight_layout()
        fig.savefig(out_dir / "figures" / "long_only_comparison.png", dpi=160)
        plt.close(fig)

    write_results_markdown(out_dir, args.data, r2_table, portfolio_summary, comparison)
    print(f"[4/5] tables and portfolio results -> {out_dir / 'tables'}")
    print(f"[5/5] human-readable summary -> {out_dir / 'RESULTS.md'}")

    display = r2_table[[c for c in ["model", "all", "bottom_30_mcap", "top_70_mcap"] if c in r2_table]].copy()
    for c in display.columns[1:]:
        display[c] = 100.0 * display[c]
    print("\nSynthetic/replication R2_oos in percent:\n" + display.to_string(index=False, float_format=lambda x: f"{x:7.3f}"))


if __name__ == "__main__":
    main()
